fun main() {
    dayOfWeek()
    println(" ")
    hourOfDay()
    println(" ")
    val fortune = getFortuneCookie()
    println("Your fortune is: $fortune")
    println(" ")
    println(canAddFish(10.0, listOf(3, 3, 3)))
    println(canAddFish(8.0, listOf(2, 2, 2), hasDecorations = false))
    println(canAddFish(9.0, listOf(1, 1, 3), 3))
    println(canAddFish(10.0, listOf(), 7, true))
    println(" ")
    whatShouldIDoToday("sad", "Sunny", 40)
    println(" ")
    println(rollDice(12))
    println(rollDice2(6))
    println(rollDice(0))
    println(" ")
    gamePlay(rollDice2(12))
}